import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./hooks/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
    "./store/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ff9385",
        "on-tertiary-container": "#000000",
        primary: "#f3ffca",
        "on-primary-fixed-variant": "#526900",
        "on-secondary-fixed-variant": "#595b63",
        "on-tertiary": "#4a0001",
        "on-surface": "#ecedf6",
        "surface-container-high": "#1c2028",
        "surface-bright": "#282c36",
        "secondary-dim": "#d2d4dd",
        "on-error-container": "#ffd2c8",
        "error-dim": "#d53d18",
        surface: "#0b0e14",
        "surface-dim": "#0b0e14",
        "primary-dim": "#beee00",
        "on-surface-variant": "#a9abb3",
        tertiary: "#ff7162",
        "secondary-fixed-dim": "#d2d4dd",
        "secondary-fixed": "#e1e2eb",
        "tertiary-container": "#f9362c",
        "on-background": "#ecedf6",
        "primary-fixed-dim": "#beee00",
        "on-tertiary-fixed-variant": "#7a0004",
        "on-tertiary-fixed": "#3a0001",
        "tertiary-fixed-dim": "#ff7c6c",
        "on-primary-container": "#4a5e00",
        "inverse-surface": "#f9f9ff",
        "inverse-on-surface": "#52555c",
        outline: "#73757d",
        "on-error": "#450900",
        "surface-container-low": "#10131a",
        "tertiary-dim": "#e2241f",
        "secondary-container": "#44474e",
        "on-secondary-fixed": "#3c3f46",
        "on-primary": "#516700",
        background: "#0b0e14",
        "primary-container": "#cafd00",
        "outline-variant": "#45484f",
        "on-secondary-container": "#ced0d9",
        "surface-variant": "#22262f",
        error: "#ff7351",
        "surface-container": "#161a21",
        secondary: "#e1e2eb",
        "inverse-primary": "#516700",
        "error-container": "#b92902",
        "surface-tint": "#f3ffca",
        "surface-container-highest": "#22262f",
        "on-secondary": "#4f5259",
        "primary-fixed": "#cafd00",
        "surface-container-lowest": "#000000",
        "on-primary-fixed": "#3a4a00",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)"],
        body: ["var(--font-inter)"],
        label: ["var(--font-inter)"],
        mono: ["var(--font-jetbrains-mono)"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      boxShadow: {
        panel: "0 18px 50px rgba(0, 0, 0, 0.28)",
        glow: "0 0 24px rgba(243, 255, 202, 0.16)",
        danger: "0 0 18px rgba(249, 54, 44, 0.22)",
        footer: "0 -4px 20px rgba(0, 0, 0, 0.4)",
      },
      keyframes: {
        "pulse-lite": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.4" },
        },
        strobe: {
          "0%, 100%": {
            borderColor: "#f9362c",
            boxShadow: "0 0 0 rgba(249, 54, 44, 0)",
          },
          "50%": {
            borderColor: "#ff7162",
            boxShadow: "0 0 12px rgba(249, 54, 44, 0.36)",
          },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-6px)" },
        },
      },
      animation: {
        "pulse-lite": "pulse-lite 2s infinite",
        strobe: "strobe 2s infinite",
        float: "float 5s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
